ARG CADDY_VERSION=2.7.6

FROM caddy:${CADDY_VERSION}-builder AS builder

RUN xcaddy build \
	--with github.com/caddy-dns/cloudflare

FROM cgr.dev/chainguard/wolfi-base:latest

RUN apk add caddy

USER root
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY --from=builder --chown=9001:9001 /srv /tr

WORKDIR /srv

USER nonroot
ENTRYPOINT [ "/usr/bin/caddy" ]
CMD ["run", "--config", "/etc/caddy/Caddyfile"]
