name: Build ffmpeg
on:
  schedule:
    - cron: "0 4 * * *" # 4am every day
  pull_request:
  push:
  merge_group:
  workflow_dispatch:
env:
  IMAGE_TAGS: latest
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}/jellyfin

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and upload packages
    runs-on: [runs-on, runner=8cpu-linux-x64, "run-id=${{ github.run_id }}"]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Generate snapshot date
        id: snapshot-date
        run: |
          echo "date=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT
          echo "epoch=$(date -u +%s)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/checkout@main
      - uses: sigstore/cosign-installer@main

      - run: |
          mkdir ffmpeg-files
          wget -q -O- https://github.com/wolfi-dev/os/raw/refs/heads/main/ffmpeg.yaml | \
          yq '.environment.contents.keyring = ["https://packages.wolfi.dev/os/wolfi-signing.rsa.pub"]|.environment.contents.repositories = ["https://packages.wolfi.dev/os"]' | \
          yq '.environment.contents.packages += ["libdrm-dev", "libva-dev"]' | \
          yq 'del(.test)' | \
          yq 'del(.subpackages[*].test)' | \
          sed 's/--enable-libzmq/--enable-libzmq \\\n        --enable-vaapi \\\n        --enable-libdrm/' \
          > ffmpeg-files/ffmpeg.melange.yaml`
          cat ffmpeg-files/ffmpeg.melange.yaml

      # - uses: chainguard-dev/actions/melange-build@main
      #   with:
      #     sign-with-temporary-key: true
      #     config: ffmpeg-files/ffmpeg.melange.yaml

      # - name: Upload packages
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Packages
      #     path: ${{ github.workspace }}/packages