name: Build Jellyfin
on:
  schedule:
    - cron: "0 4 * * *" # 4am every day
  pull_request:
  merge_group:
  workflow_dispatch:
env:
  IMAGE_TAGS: latest
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}/jellyfin

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and upload packages
    runs-on: [runs-on, runner=8cpu-linux-x64, "run-id=${{ github.run_id }}"]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Generate snapshot date
        id: snapshot-date
        run: |
          echo "date=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT
          echo "epoch=$(date -u +%s)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/checkout@main
      - uses: sigstore/cosign-installer@main

      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build-ffmpeg.yml
          branch: main
          name: ffmpeg-packages
  

      - run: |
          wget -q -O- https://github.com/wolfi-dev/os/raw/refs/heads/main/jellyfin.yaml | \
          yq '.environment.contents.keyring = ["https://packages.wolfi.dev/os/wolfi-signing.rsa.pub"]|.environment.contents.repositories = ["https://packages.wolfi.dev/os", "${{ github.workspace }}/ffmpeg-packages"]' | \
          yq 'del(.test)' > jellyfin-files/jellyfin.melange.yaml
          cat jellyfin-files/jellyfin.melange.yaml

      - uses: chainguard-dev/actions/melange-build@main
        with:
          sign-with-temporary-key: true
          config: jellyfin-files/jellyfin.melange.yaml
      #       jellyfin-files/jellyfin-web.melange.yaml
