name: Build and Push Intel Media Driver
on:
  schedule:
    - cron: "0 4 * * *" # 4am every day
  pull_request:
  merge_group:
  workflow_dispatch:
env:
  IMAGE_TAGS: latest
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}/jellyfin

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and push package
    runs-on: [runs-on, runner=8cpu-linux-x64, "run-id=${{ github.run_id }}"]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Generate snapshot date
        id: snapshot-date
        run: |
          echo "date=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT
          echo "epoch=$(date -u +%s)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/checkout@main
      - uses: sigstore/cosign-installer@main

      - name: Setup signing key
        run: 'echo "$MELANGE_SIGNING_KEY" > ${{ github.workspace }}/local-melange.rsa'
        shell: bash
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}

      - uses: chainguard-dev/actions/melange-build@main
        with:
          multi-config: intel-files/intel-gmmlib.melange.yaml
            intel-files/intel-media-driver.melange.yaml
